package Parser;

import java.util.ArrayList;
import java.util.List;
import Tokenizer.Token;
import Tokenizer.TokenType;

/**
 * A recursive descent parser that converts a linear sequence of Tokens
 * into an Abstract Syntax Tree (AST) composed of Instructions and Expressions.
 * * Language Grammar Supported:
 * program     -> instruction* EOF
 * instruction -> printStmt | assignStmt | ifStmt | repeatStmt
 * printStmt   -> ">>" expression
 * assignStmt  -> IDENTIFIER ":=" expression
 * ifStmt      -> "?" expression "=>" instruction
 * repeatStmt  -> "@" expression "=>" instruction
 */

public class Parser {
    private final List<Token> tokens;
    private int current = 0;

    /**
     * Constructs a new Parser with the given list of tokens.
     *
     * @param tokens The list of tokens generated by the Tokenizer.
     */

    public Parser(List<Token> tokens) {

        this.tokens = tokens;
    }

    /**
     * Parses the entire list of tokens into a sequence of executable instructions.
     * Skips empty newlines automatically.
     *
     * @return A list of parsed Instructions representing the program's AST.
     */

    // Step 1: The Main Loop
    public List<Instruction> parse() {
        List<Instruction> instructions = new ArrayList<>();

        while (!isAtEnd()) {
            // Skip empty newlines
            if (peek().getType() == TokenType.NEWLINE) {
                advance();
                continue;
            }
            instructions.add(parseInstruction());
        }

        return instructions;
    }

    /**
     * Determines the type of instruction based on the current token and delegates
     * to the appropriate specific parsing method.
     *
     * @return The parsed Instruction.
     * @throws RuntimeException if an unknown or invalid instruction token is encountered.
     */

    // Step 2: Figuring out which instruction we are looking at
    private Instruction parseInstruction() {
        while (peek().getType() == TokenType.NEWLINE) {
        advance();
        }
        Token token = peek();

        if (token.getType() == TokenType.PRINT) {
            return parsePrint();
        } else if (token.getType() == TokenType.IF) {
            return parseIf();
        } else if (token.getType() == TokenType.REPEAT) {
            return parseRepeat();
        } else if (token.getType() == TokenType.IDENTIFIER) {
            return parseAssign();
        }

        throw new RuntimeException("Unknown instruction starting with: " + token.getValue() + " at line " + token.getLine());
    }

    // --- Instruction Parsers ---

    /**
     * Parses a print instruction.
     * Grammar: ">>" expression
     */

    private Instruction parsePrint() {
        advance(); // Consume '>>'
        Expression expr = parseComparison(); // Parse the math/string to print
        return new PrintInstruction(expr);
    }

    /**
     * Parses a variable assignment.
     * Grammar: IDENTIFIER ":=" expression
     */

    private Instruction parseAssign() {
        String varName = advance().getValue(); // Consume the variable name

        if (advance().getType() != TokenType.ASSIGN) { // Consume ':='
            throw new RuntimeException("Expected ':=' after variable name.");
        }

        Expression value = parseComparison(); // Parse the right side of the assignment
        return new AssignInstruction(varName, value);
    }

    /**
     * Parses a conditional if statement.
     * Grammar: "?" expression "=>" instruction
     */

    private Instruction parseIf() {
        advance(); // Consume '?'
        Expression condition = parseComparison();

        if (advance().getType() != TokenType.ARROW) { // Consume '=>'
            throw new RuntimeException("Expected '=>' after if condition.");
        }

        // Note: For simplicity, this grabs the very next instruction as the body.
        // For multi-line blocks, you would read until a specific end token or EOF.
        List<Instruction> body = new ArrayList<>();
        body.add(parseInstruction());

        return new IfInstruction(condition, body);
    }

    /**
     * Parses a loop statement.
     * Grammar: "@" expression "=>" instruction
     */

    private Instruction parseRepeat() {
        advance(); // Consume '@'
        Expression count = parseComparison();

        if (advance().getType() != TokenType.ARROW) { // Consume '=>'
            throw new RuntimeException("Expected '=>' after repeat count.");
        }

        List<Instruction> body = new ArrayList<>();

        // instructions to form a multi-line block!
        while (!isAtEnd()) {
            if (peek().getType() == TokenType.NEWLINE) {
                advance();
                continue;
            }
            body.add(parseInstruction());
        }

        return new RepeatInstruction(count, body);
    }

    // --- Expression Parsers (The Math Engine) ---

    /**
     * Parses comparison operations (Lowest precedence).
     * Grammar: expression ( ( ">" | "<" ) expression )*
     */

    private Expression parseComparison() {
        Expression left = parseExpression();

        while (!isAtEnd() && (peek().getType() == TokenType.GREATER || peek().getType() == TokenType.LESS)) {
            String operator = advance().getValue();
            Expression right = parseExpression();
            left = new BinaryOpNode(left, operator, right);
        }
        return left;
    }

    /**
     * Parses addition and subtraction.
     * Grammar: term ( ( "+" | "-" ) term )*
     */

    private Expression parseExpression() {
        Expression left = parseTerm();

        while (!isAtEnd() && (peek().getType() == TokenType.PLUS || peek().getType() == TokenType.MINUS)) {
            String operator = advance().getValue();
            Expression right = parseTerm();
            left = new BinaryOpNode(left, operator, right); // Creates a node [cite: 115-117]
        }
        return left;
    }

    /**
     * Parses multiplication and division (Highest precedence math).
     * Grammar: primary ( ( "*" | "/" ) primary )*
     */

    private Expression parseTerm() {
        Expression left = parsePrimary();

        while (!isAtEnd() && (peek().getType() == TokenType.STAR || peek().getType() == TokenType.SLASH)) {
            String operator = advance().getValue();
            Expression right = parsePrimary();
            left = new BinaryOpNode(left, operator, right);
        }
        return left;
    }

    /**
     * Parses base literal values and variable lookups.
     * Grammar: NUMBER | STRING | IDENTIFIER
     */

    private Expression parsePrimary() {
        Token token = advance();

        if (token.getType() == TokenType.NUMBER) {
            return new NumberNode(Double.parseDouble(token.getValue()));
        } else if (token.getType() == TokenType.STRING) {
            return new StringNode(token.getValue());
        } else if (token.getType() == TokenType.IDENTIFIER) {
            return new VariableNode(token.getValue());
        }

        throw new RuntimeException("Expected expression but found '" + token.getValue() + "' at line " + token.getLine());
    }

    // --- Utility Methods ---

    /**
     * Returns the current token without consuming it.
     */

    private Token peek() {

        return tokens.get(current);
    }

    /**
     * Consumes the current token and returns it, advancing the pointer.
     */

    private Token advance() {
        if (!isAtEnd()) current++;
        return tokens.get(current - 1);
    }

    /**
     * Checks if the parser has reached the End of File token.
     */

    private boolean isAtEnd() {
        return peek().getType() == TokenType.EOF;
    }
}
